springfox.documentation.swagger.v2.path: /api-docs

server:
  contextPath: /api
  port: 4000
spring.jackson:
  date-format: cz.plc.prx.docker.dash.RFC3339DateFormat
  serialization.WRITE_DATES_AS_TIMESTAMPS: false