/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package cz.plc.prx.docker.dash.api;

import cz.plc.prx.docker.dash.model.WithDockerHost;

import cz.plc.prx.docker.dash.service.DockerConnectionService;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-02T07:41:20.284Z")

@Api(value = "withDockerHost", description = "the withDockerHost API")
public interface WithDockerHostApi {

    @ApiOperation(value = "set docker host configuration", notes = "set socket for docker daemon", response = Void.class, tags={ "Docker", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = Void.class) })
    
    @RequestMapping(value = "/withDockerHost",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<DockerConnectionService> withDockerHostPost(@ApiParam(value = "The user to create."  )  @Valid @RequestBody WithDockerHost user);

}
